### ISSUE TITLE
Create a small database in case file hash not provided

### ISSUE THREAD

**Issue by likkai** [AplhaSlayer1964/kemono-dl#33]
As stated in the release page, kemono does not provide file hash for some files. So maybe you could try making a small database file used to store the name of the downloaded items? If the file hash is not provided then repeated download can be prevented by checking the database file.

**Comment by AplhaSlayer1964** [comment]
Well if you use the `--archive file.txt` it will log all the posts that are downloaded to file.txt and skip them next time you run the script. The main point of the hash checking was to stop redownloading files of posts that were not marked with `--archive` because of some error. I just also ended up making it default behavior because I can hopefully grantee kimonos hashes are at least correct for verifying the download.

**Comment by likkai** [comment]
One more question, if i run the command by using `--archive file.txt` and the logs are saved in the file, how do set the downloader to use this file as a reference to check which images have been downloaded? Is it done so by using `--archive file.txt` again?

**Comment by AplhaSlayer1964** [comment]
> One more question, if i run the command by using `--archive file.txt` and the logs are saved in the file, how do set the downloader to use this file as a reference to check which images have been downloaded? Is it done so by using `--archive file.txt` again?

yes when you call `archive file.txt` it reads from the file and skips anything already written in it and writes anything new that is saved.

**Comment by likkai** [comment]
Thanks for the help, love your amazing tool
