### ISSUE TITLE
Do not create an attachment folder&Give indexing numbers to the first image as well

### ISSUE THREAD

**Issue by undecimated** [AplhaSlayer1964/kemono-dl#34]
1
I would like to download all files to [{date}] [{post_id}] {post_title} without creating an attachments folder.
I think it would be easier to browse without the attachments folder, as the hierarchy would not be so deep.
2
I want to add indexing numbers to the very first image as well. For example, [0]_.
This is often a thumbnail image, so we want it to appear first.

Thanks for great program.
I'm sorry my English is not good.

**Comment by AplhaSlayer1964** [comment]
So I manly have the attachments folder because posts can have attachments and have a post file that is separate from the other files but it could also be a duplicate. I guess you are also referring to the post file to have the index [0]. I still need to think of a better file structure for everything honestly. I have been pretty busy lately so haven't been able to do much with this program. I am trying to re work some stuff so hopefully I get around to it. Feel free to make a fork that better suits your folder layout needs in the mean time.

**Comment by undecimated** [comment]
I understand.
Thank you!
