### ISSUE TITLE
Duplicate file downloaded

### ISSUE THREAD

**Issue by YoRHaAlter** [AplhaSlayer1964/kemono-dl#63]
### Description

First of all thank you very much for the downloader. It helped me a lot.

The first issue is about the downloader version 2022.02.10.
Recently there has been an issue with duplicate files.
After a period of time, when I download the same post again, in some cases two sets of identical files with different names are downloaded.
I noticed that the downloader prevents file duplication by recording the filename in the json file.
I speculate that the reason may be related to the website changing the file name.
Is there any way to prevent duplicate file downloads? For example, the downloaded file is named with its md5, or the md5 of the downloaded file is recorded with a json file.

Another question about the 2022.02.21 version of the downloader.
The new file naming does not seem to recognize files that have been downloaded in the past. This causes the downloader to redownload all files.
Is there a way to read a record of files that have been downloaded in the past? Or batch rename files that have been downloaded in the past?

Thanks again!

### Service, User ID, Post ID

- Site:kemono
- Service:fanbox
- User ID:3316400
- Post ID:3416053

### Additional comments

Below is a link to an example post where the first problem occurs.
https://kemono.party/fanbox/user/3316400/post/3416053
The file with sequence number 1 was originally named [01]_8597f433-3ffa-4c1e-9d12-ede4d28d36b7, and now the same file named [01]_e756dd46-cdf8-4859-961a-f8f39b4c58ef is downloaded again.

**Comment by AplhaSlayer1964** [comment]
So I don't use the json for recording what files have been downloaded. I check the files hash since the kemono servers have the files hash available, though sometimes they are wrong. Now first it checks to see if a file with the same name exists then if it does it checks the hash. I guess I never thought the file names would change, probably if the post is updated it has a chance. I will have to work on a better method of checking then.

For the pre release version I know the new file naming isn't the best and I do want to change it to be dynamic like the path naming. I manly need to find a better way of naming the "extra" files like content, comments, embed, etc. I will also look into making a format converter for older versions of the downloader.

**Comment by bog4t** [comment]
You may be downloading [different revisions of the same post](https://github.com/mikf/gallery-dl/issues/1216#issuecomment-760469575).

**Comment by AplhaSlayer1964** [comment]
> You may be downloading [different revisions of the same post](https://github.com/mikf/gallery-dl/issues/1216#issuecomment-760469575).

The issue referenced there wouldn't have caused the problem they referenced as the duplicate posts all had unique post ids so the duplicate files would have never been in the same folder. I am also unaware how updated posts are handled by kemono.pary but it seems like the old content is deleted and replaced now. Also the duplicate posts referenced in that issue were not from them updating the post. If you go look the patreon user uploaded three posts with the same name minutes apart.
