### ISSUE TITLE
When using the --from-file option, only certain users are excluded from downloading attachments.

### ISSUE THREAD

**Issue by YTOAA** [AplhaSlayer1964/kemono-dl#68]
Hello, I'm not good at English. Some of the posts from certain users can be uploaded simultaneously with zip files and images, taking up too much space. 
Of course, when downloading only one post -skip-filetypes EXT option is used to exclude attachments, but --from-file option is used together to download posts from multiple users. Is there any way to exclude downloading attachments only for certain users using the --from-file option? 
Alternatively, it would be great if you could use the --from-file option to exclude a particular user post, a particular confirmed file.

**Comment by AplhaSlayer1964** [comment]
> Of course, when downloading only one post -skip-filetypes EXT option is used to exclude attachments, but --from-file option is used together to download posts from multiple users. Is there any way to exclude downloading attachments only for certain users using the --from-file option? 
 
No, `--from-file` just acts as if you passed each url one at a time so there is no option to have specific links to have specific options.

> Alternatively, it would be great if you could use the --from-file option to exclude a particular user post, a particular confirmed file.

Are you asking if a user link is passed to ignore a specific post and or a specific file? If so that shouldn't be to hard but currently I don't have time to work on this project much. Feel free to make a pull request to add the feature itself.
